version: 2
jobs:
  release-staging:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/th-form
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python-pip libpython-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            sudo pip install -q awscli --upgrade
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $QA_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $QA_AWS_SECRET_ACCESS_KEY
      - run:
          name: Update NPM
          command: |
            sudo npm install -g npm@latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: NPM Build
          command: |
            npm run build
      - run:
          name: Upload to S3
          command: |
            aws s3 cp ~/th-form/dist/THForm.bundle.js s3://qa-th-form/THForm.js --acl public-read
  release-production:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/th-form
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python-pip libpython-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            sudo pip install -q awscli --upgrade
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $PROD_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $PROD_AWS_SECRET_ACCESS_KEY
      - run:
          name: Update NPM
          command: |
            sudo npm install -g npm@latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: NPM Build
          command: |
            npm run build
      - run:
          name: Upload to S3
          command: |
            aws s3 cp ~/th-form/dist/THForm.bundle.js s3://prod-th-form/THForm.js --acl public-read
  build-and-test:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/th-form
    steps:
      - checkout
      - run:
          name: Update NPM
          command: |
            sudo npm install -g npm@latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: NPM Build
          command: |
            npm run build
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Sonar analysis & publish results
          command: bash ./scripts/devops/sonar.sh

workflows:
  version: 2
  deploy:
    jobs:
      - release-staging:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*QA/
            branches:
              ignore: /.*/
      - release-production:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build-and-test:
          filters:
            branches:
              only: /.*/
