version: 2
jobs:
  release-staging:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/th-form
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python-pip libpython-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            pip install -q awscli --upgrade
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $QA_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $QA_AWS_SECRET_ACCESS_KEY
      - run:
          name: NPM Build
          command: |
            npm run build
      - run:
          name: Upload to S3
          command: |
            aws s3 sync ./blob/master/dist/THForm.bundle.js s3://th-form/THForm.js
  release-production:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/th-form
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python-pip libpython-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            pip install -q awscli --upgrade
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $PROD_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $PROD_AWS_SECRET_ACCESS_KEY
      - run:
          name: NPM Build
          command: |
            npm run build
      - run:
          name: Upload to S3
          command: |
            aws s3 sync ./blob/master/dist/THForm.bundle.js s3://th-form/THForm.js

workflows:
  version: 2
  deploy:
    jobs:
      - release-staging:
          filters:
            branches:
              only: feature/circleci-deploy
      - release-production:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
